config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, except: :index, shallow: true
      end
    end
  end

  concern :votable do
    member do
      post :vote
      post :unvote
    end
  end

  concern :commentable do
    resources :comments
  end

  get '/search', to: "search#search"

  resources :questions, concerns: [:votable, :commentable] do
    resources :subscribes, only: %i[create destroy]
    resources :answers, except: :index, shallow: true, concerns: [:votable, :commentable] do
      member do
        post :choose_best
      end
    end
  end

  resources :attachments, only: :destroy

  mount ActionCable.server => "/cable"

end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable
  include Subscribable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  belongs_to :user

  validates :title, :body, presence: true

  after_save :auto_subscribe

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  private

  def auto_subscribe
    subscribes.create!(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: %i[show]
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions, include: [], root: "questions"
  end

  def show
    respond_with @question
  end

  def create
    respond_with(@question = current_resource_owner.questions.create(question_params))
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  before_action :build_answer, only: %i[show]
  before_action :check_subscribe, only: %i[show]
  after_action :publish_question, only: %i[create]

  respond_to :html, :js

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    gon.question_id = @question.id
    respond_with(@question)
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit; end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def check_subscribe
    @subscribe = @question.subscribes.first
  end

  def build_answer
    @answer = @question.answers.build
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      "questions",
      ApplicationController.render_with_signed_in_user(
        current_user,
        partial: "questions/question",
        locals: { question: @question }
      )
    )
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: @question, local: true do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_field :body

  p Attachments:
  p id="attachments"
    =f.fields_for :attachments, @question.attachments.build do |a|
      = render "shared/attachment_fields", f: a
    .links
      = link_to_add_association 'Add file', f, :attachments, partial: "shared/attachment_fields"

  p= f.submit 'Create'

app/views/questions/_question.html.slim
tr
  td= question.title
  td= question.body
  td= question.user.email
  td= link_to 'Show', question_path(question)
  - if can?(:destroy, question)
    td= link_to 'Delete', question_path(question), method: :delete, data: { confirm: 'Are u sure ?'}

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  H1 All questions:

  table id="questions-list"
    tr
      th Question title
      th Question body
      th Author

    = render @questions

  - if can?(:create, Question)
    p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
p= render "shared/errors", resource: @question

p= render "form"

p= link_to "Back", :back

app/views/questions/show.html.slim
- cache @question do
  .errors_question
    p= render "shared/errors", resource: @question

  .question
    H1.title= @question.title
    p.body= @question.body
    p Attachments:
    ul
      - @question.attachments.each do |a|
        .attachment_file id="attachment-#{a.id}"
          li = link_to a.file.identifier, a.file.url
          - if current_user&.author_of?(@question)
            = link_to 'Delete file', attachment_path(a),remote: true,
                                                        method: :delete,
                                                        class: "text-muted links-decor",
                                                        data: { confirm: 'Are u sure ?' }
    - if can?(:edit, @question)
      p= link_to "Edit question", "", class: "edit-question-link", data: { id: @question.id }
      p= form_for @question, remote: true, html: { id: "edit-question-#{@question.id}" } do |f|
        = f.label :title, "Title: "
        = f.text_field :title
        = f.label :body, "Question text: "
        = f.text_area :body
        = f.submit "Save"
        = f.button "Hide", class: "edit-question-hide", data: { id: @question.id }

  .question_comments
    =render @question.comments
  p= render "shared/new_comment", resource: @question if user_signed_in?

  .question_votement id="question_votement"
    - if can?(:vote, @question)
      = link_to "+", polymorphic_path(@question, action: :vote), class: "question-vote badge badge-success",
                                                    method: :post,
                                                    remote: true
    .question_rating class="badge badge-light"
      = @question.rating
    - if can?(:unvote, @question)
      = link_to "-", polymorphic_path(@question, action: :unvote), class: "question-vote badge badge-danger",
                                                      method: :post,
                                                      remote: true

  .question_subscribe id="question_subscribe"
    - if current_user && @question.subscribe_by(current_user).empty?
      = link_to "Follow this question", question_subscribes_path(@question), class: "question-subscribe badge badge-info",
              method: :post,
              remote: true
    - if @question.subscribe_by(current_user).any?
      = link_to "Unsubscribe", question_subscribe_path(@question, @subscribe), class: "question-unsubscribe badge badge-light",
              method: :delete,
              remote: true,
              data: { confirm: 'Are u sure ?' }

  H4 List of answers:

  .answers id="answers"
    = render @question.answers.sort_from_best_answer

  .errors
    p= render "shared/errors", resource: @answer

  p= render "answers/new" if user_signed_in?

  p= link_to "Back", questions_path

app/views/questions/update.js.erb
<% if @question.errors.present? %>
    $('.errors_question').html('<%= j render 'shared/errors', resource: @question %>');
<% else %>
    $('.title').html('<%= j @question.title %>')
    $('.body').html('<%= j @question.body %>')

    $('.question').on('click', '.edit-question-link', function(e) {
        e.preventDefault();
        $(this).hide();
        question_id = $(this).data('id');
        $("form#edit-question-" + question_id).show();
    });

    $('.question').on('click', '.edit-question-hide', function(e) {
        e.preventDefault();
        $(this).hide;
        question_id = $('.edit-question-link').data('id');
        $("form#edit-question-" + question_id).hide();
        $('.edit-question-link').show();
        $('.errors_question').html('');
    });
<% end %>