config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, except: :index, shallow: true
      end
    end
  end

  concern :votable do
    member do
      post :vote
      post :unvote
    end
  end

  concern :commentable do
    resources :comments
  end

  get '/search', to: "search#search"

  resources :questions, concerns: [:votable, :commentable] do
    resources :subscribes, only: %i[create destroy]
    resources :answers, except: :index, shallow: true, concerns: [:votable, :commentable] do
      member do
        post :choose_best
      end
    end
  end

  resources :attachments, only: :destroy

  mount ActionCable.server => "/cable"

end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy

  validates :body, presence: true

  after_save :digest_for_subscribers

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  scope :sort_from_best_answer, -> { order(best_answer_id: :desc) }

  def make_choice
    ActiveRecord::Base.transaction do
      question.answers.update_all(best_answer_id: false)
      update!(best_answer_id: true)
    end
  end

  private

  def digest_for_subscribers
    @subscribed_users = question.subscribes.map(&:user)
    SubscribedQuestionJob.perform_later(@subscribed_users, self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[show]
  before_action :set_question, only: %i[create]
  before_action :set_answer, only: %i[destroy update choose_best]
  after_action :broadcast_answer, only: %i[create]

  respond_to :js

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    respond_with(@question, @answer.save)
  end

  def choose_best
    @answer.make_choice
    redirect_to question_path(@answer.question)
  end

  def update
    @answer.update(answer_params)
    respond_with(@question = @answer.question, @answer)
  end

  def destroy
    respond_with(@answer.destroy)
  end

  private

  def broadcast_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast "questions/#{@answer.question.id}/answers", {
        answer: @answer,
        answer_attachments: @answer.attachments,
        question_user: @question.user_id,
        answer_rating: @answer.rating,
        question_id: @question.id
    }
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: %i[create]
  before_action :load_answer, only: %i[show]
  authorize_resource

  def show
    respond_with @answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    flash[:notice] = 'Answer was successfully created.' if @answer.save
    respond_with(@answer)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  ul class="card" id="answer-#{answer.id}"
    p class="best_answer_id" = answer.best_answer_id
    li= answer.body
    .attachments Attachments:
    - answer.attachments.each do |a|
      .attachment_file id="attachment-#{a.id}"
        li= link_to a.file.identifier, a.file.url
        - if can?(:destroy, a)
          = link_to 'Delete file', attachment_path(a), remote: true,
                                                       method: :delete,
                                                       class: "text-muted links-decor",
                                                       data: {confirm: 'Are u sure ?'}
    - if can?(:choose_best, answer)
      p= link_to "Mark as the best", choose_best_answer_path(answer), class: "best-answer-link", data: { answer_id: answer.id }, method: :post
    - if current_user&.author_of?(answer)
      p
        = link_to 'Delete', answer_path(answer), remote: true, method: :delete, data: {confirm: 'Are u sure ?' }
        = " | "
        = link_to 'Edit', "", class: "edit-answer-link", data: { answer_id: answer.id }

        = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
          = f.label :body, "Answer"
          = f.text_area :body
          = f.submit "Save"

    .answer_comments id="answer-comments-#{answer.id}"
      = render answer.comments
    p= render "shared/new_comment", resource: answer if user_signed_in?

    .answer_votement
      - if can?(:vote, answer)
        = link_to "+", polymorphic_path(answer, action: :vote), class: "answer-vote badge badge-success",
                method: :post,
                remote: true,
                data: { answer_id: answer.id }
      .answer_rating class="badge badge-light" id="answer-rating-#{answer.id}"
        = answer.rating
      - if can?(:unvote, answer)
        = link_to "-", polymorphic_path(answer, action: :unvote), class: "answer-vote badge badge-danger",
                method: :post,
                remote: true,
                data: { answer_id: answer.id }

app/views/answers/_new.html.slim
p= form_for [@question, @answer], remote: true, data: { type: :json } do |f|
  .field
    p= f.label :body, "Write your answer: "
    p= f.text_area :body, id: :answer_body, rows: 7, col: 60
  p id="attachments"
    = f.fields_for :attachments, @answer.attachments.build do |a|
      = render "shared/attachment_fields", f: a
    .links
      = link_to_add_association 'Add file', f, :attachments, partial: "shared/attachment_fields"
  p= f.submit 'Answer the question'

app/views/answers/create.js.erb
$('.errors').html('<%= j render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
    $('.answers').append('<%= j render @answer %>');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
  $('.errors_question').html('<%= j render 'shared/errors', resource: @answer %>');
<% else %>
  $("ul#answer-<%= @answer.id %>").remove();
<% end %>

app/views/answers/show.html.slim
= render "shared/errors", resource: @answer

app/views/answers/update.js.erb
$('.errors').html('<%= j render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
    $('.answers').html('<%= j render @question.answers.sort_from_best_answer %>')

    if ($('.best_answer_id')[0].innerHTML != false && $('.best_answer_id')[0].innerHTML != "") {
        $('ul[id^=answer]')[0].classList.add('best_answer');
    }
<% end %>

$('.answers').on('click', '.edit-answer-link', function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $("form#edit-answer-" + answer_id).show();
});